### ISSUE TITLE
When I can download lib?

### ISSUE THREAD

**Issue by Programistich** [octopus-energy/TeslaAndroidAuth#1]

**Comment by nrobi144** [comment]
@Programistich we plan on publishing this week/early next week

**Comment by Programistich** [comment]
Maybe u need some help? I can contribute

**Comment by nrobi144** [comment]
@Programistich it should be available now on `mavenCentral`:
```
implementation("energy.octopus:tesla-android-auth:0.1")
```

It might need some adjustments, which we'll be exploring sometime in the near future:
- Logging mechanism - possibility to turn that off in debug builds
- Right now only the final `authToken` is sent back from [Step 4](https://tesla-api.timdorr.com/api-basics/authentication#step-4-exchange-bearer-token-for-access-token), we might want to break that down, and progress with the steps based on subscriber needs + publish intermediate tokens/codes as well.

Feel free to create issues/feature-requests, any contribution is welcome, I can help with information about the project

**Comment by Programistich** [comment]
You return access token from OwnerApi?
What about refresh this token? Or how much time he live?

**Comment by nrobi144** [comment]
@Programistich [Refresh token](https://tesla-api.timdorr.com/api-basics/authentication#refreshing-an-access-token) is not done yet, you could do that with the `access token` you get back from the library

If you feel that's something you'd like to be handled by this library, please create an issue

**Comment by Programistich** [comment]
Its okey
Mb we can connect in some messanger? 
I think good idea for create lib Tesla Api
